[project]
name = "ner-modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deeplotx>=0.8.8",
    "json-repair>=0.48.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.1",
    "tensorboard>=2.20.0",
    "tqdm>=4.67.1",
]
